[mongo]
uri = "mongodb+srv://chuangsopit_db_user:DBKSW4Y2m8E.mUq@cluster0.ffnx7sx.mongodb.net/?appName=Cluster0"
database = "sso_app"

[snowflake]
account   = "ty20879.ap-southeast-7.aws"
user      = "kaitokid"
password  = "bicxmWQK83GY5dP"
warehouse = "COMPUTE_WH"
database  = "SSO_DB"
schema    = "PUBLIC"
role      = "ACCOUNTADMIN"